version: 2.1
orbs:
  python: circleci/python@1.2
  heroku: circleci/heroku@0.0.10
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Setup testing environment
          command: |
            pip install -r requirements.txt
            echo $HOME
      - run:
          name: Run Tests
          command: |
            coverage run --source="." manage.py test
            coverage report
            coverage html
      - store_artifacts:
          path: htmlcov
workflows:
  test-and-deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          requires:
            - build-and-test
