version: 2.1
orbs:
  python: circleci/python@1.2
  heroku: circleci/heroku@0.0.10
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
workflows:
  tests:
    jobs:
      - build-and-test
  heroku_deploy:
    when: on_success
    jobs:
      - heroku/deploy-via-git
